development:
  adapter: postgresql
  encoding: unicode
  database: spdweb_dev
  pool: 50
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  database: spdweb_prod
  password:
  pool: 50%
